# Base image, e.g. tensorflow/tensorflow:1.7.0
FROM tensorflow/tensorflow:1.8.0

LABEL maintainer='Valentin Kozlov'
# Dogs breed detector

RUN apt-get update && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

# Set the working directory
WORKDIR /home

# Copy the current directory contents into the container at /home
#ADD . /home

# Install python packages listed in requirements.txt
COPY requirements.txt /home/
RUN python -m pip --no-cache-dir install -r /home/requirements.txt \
### (OPTIONAL!) If you want to use Jupyter, uncomment:
#        jupyter \
#        jupyterlab && \
#   python -m ipykernel.kernelspec \
###
    && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

### (OPTIONAL!) If you want to use Jupyter, uncomment: 
## Set up our notebook config.
#COPY docker/jupyter/jupyter_notebook_config.py /root/.jupyter/
#COPY docker/jupyter/run_jupyter.sh /
## For Jupyter terminal
#ENV SHELL /bin/bash
#
## REMINDER: Tensorflow Docker Images already EXPOSE ports 6006 and 8888
#EXPOSE 8888
###

