# Base image, e.g. tensorflow/tensorflow:1.7.0
FROM tensorflow/tensorflow:1.8.0

LABEL maintainer='Valentin Kozlov'
# Dogs breed detector

RUN apt-get update && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*


# Set the working directory
WORKDIR /home

# Script to run pylint
COPY dogs_breed_det/tests/run_pylint.sh /home

# Copy the current directory contents into the container at /home
ADD . /home

# Install pylint and python packages listed in requirements.txt
RUN python -m pip --no-cache-dir install pylint \
    -r /home/requirements.txt && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

