##################
# Run from ~/dogs_breed_det as
# $> docker build -t dockerimage -f docker/Dockerfile.dev .
# Then use as
# $> docker run -ti -v ~/dogs_breed_det:/app dockerimage /bin/bash
##################
# Base image, e.g. tensorflow/tensorflow:1.7.0
FROM tensorflow/tensorflow:1.8.0

LABEL maintainer='V.Kozlov (KIT)'
# Dogs breed detector as example for DEEPaaS API

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --no-install-recommends \
         git \
         curl \
         wget \
         python-setuptools \
         python-pip \
         python-wheel && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

# install rclone
RUN wget https://downloads.rclone.org/rclone-current-linux-amd64.deb && \
    dpkg -i rclone-current-linux-amd64.deb && \
    apt install -f && \
    rm rclone-current-linux-amd64.deb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*


# Set LANG environment
ENV LANG C.UTF-8

# Set the working directory
WORKDIR /app

# Install python packages listed in requirements.txt
COPY requirements-dev.txt /root
RUN pip --no-cache-dir install -r /root/requirements-dev.txt \
### (OPTIONAL!) If you want to use Jupyter, uncomment:
#        jupyter \
#        jupyterlab && \
#   python -m ipykernel.kernelspec \
###
    && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

### (OPTIONAL!) If you want to use Jupyter, uncomment: 
## Set up our notebook config.
#COPY docker/jupyter/jupyter_notebook_config.py /root/.jupyter/
#COPY docker/jupyter/run_jupyter.sh /
## For Jupyter terminal
#ENV SHELL /bin/bash
#
## REMINDER: Tensorflow Docker Images already EXPOSE ports 6006 and 8888
#EXPOSE 8888
###

